// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKHtSmOmi59I6K42Va-iqOF-YrwXtSOGs',
    appId: '1:2641663745:web:81b7fb2ddded5613cced00',
    messagingSenderId: '2641663745',
    projectId: 'todo-144c2',
    authDomain: 'todo-144c2.firebaseapp.com',
    storageBucket: 'todo-144c2.appspot.com',
    measurementId: 'G-FE68D52ZRX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4rmey0arXZXT_uU8uTAJfDPkx6veVEvs',
    appId: '1:2641663745:android:f77ffd5f82d9ae6acced00',
    messagingSenderId: '2641663745',
    projectId: 'todo-144c2',
    storageBucket: 'todo-144c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6jOUqDL_3J8Khi4uFPAPFpvKJLBciCeU',
    appId: '1:2641663745:ios:1344561ff1a50238cced00',
    messagingSenderId: '2641663745',
    projectId: 'todo-144c2',
    storageBucket: 'todo-144c2.appspot.com',
    iosClientId: '2641663745-aq1pinme7ahsdlqh5gulddetm5vb512b.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6jOUqDL_3J8Khi4uFPAPFpvKJLBciCeU',
    appId: '1:2641663745:ios:1344561ff1a50238cced00',
    messagingSenderId: '2641663745',
    projectId: 'todo-144c2',
    storageBucket: 'todo-144c2.appspot.com',
    iosClientId: '2641663745-aq1pinme7ahsdlqh5gulddetm5vb512b.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );
}
